export { foldpAuto, foldpManual, foldpRC } from "./foldp";
export { accumAuto, accumManual, accumRC } from "./accum";
export { switchHoldRC, switchHoldManual, switchHoldAuto } from "./switch-hold";
export { switchMap } from "./switch-map";
export { switchB, switchE } from "./switch";
export { toStream } from "./to-stream";
export { gate } from "./gate";
export { apply } from "./apply";
export { filterApply } from "./filter-apply";
export { tag } from "./tag";
export { flatMap, flatten, map, of, zip } from "./store-utils/store-utils";
export { tracker } from "./tracker";
